config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'
  resources :posts do
  	get :cancel, on: :collection
  end
  get 'tags/:tag', to: 'posts#index', as: "tag"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings

  #Getter and Setter for all_tags vertial attribute
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
        Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end


  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save 
        format.js # Will search for create.js.erb
      else
        format.html { render root_path }
      end
    end
  end

  def edit
    respond_to do |format|
      format.html {redirect_back(fallback_location: root_path)}
      format.js
    end
  end

  def update
    if @post.update_attributes(post_params)
      respond_to do |format|
        format.html {redirect_back(fallback_location: root_path)}
        format.js
      end
    end
  end

  def destroy 
    @post.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end
    def post_params
      params.require(:post).permit(:author, :content, :all_tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GenericTagging</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_edit.html.erb
<div class="col-md-11 edit-form" style="padding: 10px 20px">
  <div class="panel panel-default devise-bs">
    <div class="panel-heading" style="background:#353d47; color: white;">
      <h4>Post</h4>
    </div>
    <div class="panel-body">
      <%= form_for(@post , url: post_path(@post), remote: true) do |f| %>
        <div class="form-group">
        <label>Name</label>
          <%= f.text_field :author, placeholder: "Author name",class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Post</label>
          <%= f.text_area :content, placeholder: "Your post", rows: 5,class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Tags</label>
          <%= f.text_field :all_tags, placeholder: "Tags separated with comma",class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Post", class: "btn btn-success btn-sm"%>
          <%= link_to "cancel", cancel_posts_path(id: @post), class: 'btn btn-sm btn-default',remote: true %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_new.html.erb
<div class="col-md-11 post-form" style="padding: 10px 20px">
  <div class="panel panel-default devise-bs">
    <div class="panel-heading" style="background:#353d47; color: white;">
      <h4>Post</h4>
    </div>
    <div class="panel-body">
      <%= form_for(Post.new , remote: true) do |f| %>
        <div class="form-group">
        <label>Name</label>
          <%= f.text_field :author, placeholder: "Author name",class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Post</label>
          <%= f.text_area :content, placeholder: "Your post", rows: 5,class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Tags</label>
          <%= f.text_field :all_tags, placeholder: "Tags separated with comma",class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Post", class: "btn btn-success btn-sm"%>
        </div>
        <% if params[:action] == "edit" %>
          <%= link_to "cancel" %>
        <%end%>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<%= div_for post do %>
  <div>
    <div>
      <b>Author Name:</b>
      <%= h(post.author) %>
    </div>
    <sup>From <%= time_ago_in_words(post.created_at)%></sup><br />
    <div>
      <b>Post:</b>
      <%= h(post.content) %>
    </div>
    <div>
      <b>Tags:</b>
      <%=raw tag_links(post.all_tags)%>
    </div>
    <br>
    <div>
      <%= link_to 'Delete', post_path(post), method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs" %>
      <%= link_to 'Edit', edit_post_path(post),remote: true, class: "btn btn-warning btn-xs" %>
    </div>
    <hr/>
  </div>
<% end %>

app/views/posts/cancel.js.erb
$('.edit-form').show(100, function(){
$(this).replaceWith("<%= j render('posts/new') %>");
});

app/views/posts/create.js.erb
var new_post = $("<%= escape_javascript(render(partial: @post))%>").hide();
$('#posts').prepend(new_post);
$('#post_<%= @post.id %>').fadeIn('slow');
$('#new_post')[0].reset();

app/views/posts/destroy.js.erb
$('#post_<%= @post.id %>').fadeOut(500, function(){
$(this).remove();
$(this).find('hr:last').remove();
});

app/views/posts/edit.js.erb
$('.post-form').fadeIn(500, function(){
$(this).replaceWith("<%= j render('posts/edit') %>");
});

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-5">
    <%= render partial: "posts/new" %>
  </div>
  <div class="col">
    <h3 style="font-weight: bold;color: hsla(0, 0%, 20%, 0.78);">Tags List</h3>
    <% tag_cloud Tag.counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>
  <hr/>
  <div class= "col-md-7" id="posts">
    <%= render partial: @posts.reverse %>
  </div>
</div>

app/views/posts/update.js.erb
$('#post_<%= @post.id %>').fadeOut(500, function(){
$(this).replaceWith("<%= j render @post %>");
});

$('.edit-form').show(100, function(){
$(this).replaceWith("<%= j render('posts/new') %>");
});